# Generated by Django 4.2.7 on 2023-11-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(default=None, upload_to='courses/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='courses',
            unique_together={('name', 'fk_topic')},
        ),
        migrations.AlterModelTable(
            name='courses',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('index', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('fk_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningEnglish.courses')),
            ],
            options={
                'db_table': 'lesson',
                'ordering': ['created_date'],
                'unique_together': {('name', 'fk_courses')},
            },
        ),
    ]
