# Generated by Django 4.2.7 on 2023-11-24 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar',
            name='fk_question',
        ),
        migrations.RemoveField(
            model_name='listen',
            name='fk_question',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='fk_question',
        ),
        migrations.RemoveField(
            model_name='word',
            name='fk_question',
        ),
        migrations.AddField(
            model_name='question',
            name='fk_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='LearningEnglish.lesson'),
        ),
    ]
