# Generated by Django 4.2.7 on 2023-11-24 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0002_remove_grammar_fk_question_remove_listen_fk_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleGrammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'titlegrammar',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grammar',
            name='fk_titlegrammar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grammars', to='LearningEnglish.titlegrammar'),
        ),
    ]
