# Generated by Django 4.2.7 on 2023-11-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0002_alter_courses_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courses',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='courses',
            name='fk_topic',
        ),
        migrations.AddField(
            model_name='courses',
            name='fk_topic',
            field=models.ManyToManyField(blank=True, null=True, to='LearningEnglish.topic'),
        ),
    ]
