# Generated by Django 4.2.7 on 2023-11-22 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0003_alter_courses_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(default=None, upload_to='courses/%Y/%m')),
                ('description', models.TextField(blank=True, null=True)),
                ('topics', models.ManyToManyField(blank=True, null=True, to='LearningEnglish.topic')),
            ],
            options={
                'db_table': 'course',
                'ordering': ['created_date'],
            },
        ),
        migrations.AlterField(
            model_name='lesson',
            name='fk_courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='LearningEnglish.course'),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
