# Generated by Django 4.2.7 on 2023-11-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0004_course_alter_lesson_fk_courses_delete_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='topics',
            new_name='topic',
        ),
    ]
