# Generated by Django 4.2.7 on 2023-11-29 04:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0006_alter_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='paragraph',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
