# Generated by Django 4.2.7 on 2023-12-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0007_alter_reading_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_category_wlrg',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson_category_wlrg',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson_category_wlrg',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
