# Generated by Django 4.2.7 on 2023-12-04 03:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0009_ranking_score_process_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='recipe',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
