# Generated by Django 4.2.8 on 2023-12-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0011_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson_category_wlrg',
            old_name='fk_Category',
            new_name='fk_category',
        ),
        migrations.RenameField(
            model_name='lesson_category_wlrg',
            old_name='fk_Lesson',
            new_name='fk_lesson',
        ),
        migrations.AlterUniqueTogether(
            name='lesson_category_wlrg',
            unique_together={('id_WLRG', 'fk_lesson', 'fk_category')},
        ),
    ]
