# Generated by Django 4.2.8 on 2024-03-15 02:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0012_rename_fk_category_lesson_category_wlrg_fk_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sound', models.FileField(blank=True, default=None, null=True, upload_to='listening_file/%Y/%m')),
                ('fk_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listening_lesson', to='LearningEnglish.lesson')),
            ],
            options={
                'db_table': 'listening',
            },
        ),
        migrations.CreateModel(
            name='QuestionGrammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('correct_answer', models.CharField(max_length=5, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('ft_answer', models.CharField(max_length=255, null=True)),
                ('sd_answer', models.CharField(max_length=255, null=True)),
                ('td_answer', models.CharField(max_length=255, null=True)),
                ('fh_answer', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'question_grammar',
            },
        ),
        migrations.CreateModel(
            name='QuestionListening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('correct_answer', models.CharField(max_length=5, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('fk_listen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_listening', to='LearningEnglish.listening')),
            ],
            options={
                'db_table': 'question_listening',
            },
        ),
        migrations.CreateModel(
            name='QuestionReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('correct_answer', models.CharField(max_length=5, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('ft_answer', models.CharField(max_length=255, null=True)),
                ('sd_answer', models.CharField(max_length=255, null=True)),
                ('td_answer', models.CharField(max_length=255, null=True)),
                ('fh_answer', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'question_reading',
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson_category_wlrg',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lesson_category_wlrg',
            name='fk_category',
        ),
        migrations.RemoveField(
            model_name='lesson_category_wlrg',
            name='fk_lesson',
        ),
        migrations.DeleteModel(
            name='Listen',
        ),
        migrations.RemoveField(
            model_name='question',
            name='fk_lesson',
        ),
        migrations.AddField(
            model_name='reading',
            name='fk_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_lesson', to='LearningEnglish.lesson'),
        ),
        migrations.AddField(
            model_name='titlegrammar',
            name='fk_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titlegrammar_lesson', to='LearningEnglish.lesson'),
        ),
        migrations.AddField(
            model_name='word',
            name='fk_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_lesson', to='LearningEnglish.lesson'),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='fk_title_grammar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grammars', to='LearningEnglish.titlegrammar'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Lesson_Category_WLRG',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='questionreading',
            name='fk_reading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_reading', to='LearningEnglish.reading'),
        ),
        migrations.AddField(
            model_name='questiongrammar',
            name='fk_grammar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_grammar', to='LearningEnglish.grammar'),
        ),
    ]
