# Generated by Django 4.2.8 on 2024-03-15 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0013_listening_questiongrammar_questionlistening_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionlistening',
            old_name='fk_listen',
            new_name='fk_listening',
        ),
    ]
