# Generated by Django 4.2.8 on 2024-03-15 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0014_rename_fk_listen_questionlistening_fk_listening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiongrammar',
            name='fk_grammar',
        ),
        migrations.AddField(
            model_name='questiongrammar',
            name='fk_titlegrammar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_grammar', to='LearningEnglish.titlegrammar'),
        ),
    ]
