# Generated by Django 4.2.8 on 2024-03-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0015_remove_questiongrammar_fk_grammar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
