# Generated by Django 4.2.8 on 2024-03-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0016_lesson_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titlegrammar',
            name='fk_lesson',
        ),
        migrations.RemoveField(
            model_name='word',
            name='fk_lesson',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='fk_title_grammar',
        ),
        migrations.DeleteModel(
            name='QuestionGrammar',
        ),
        migrations.DeleteModel(
            name='TitleGrammar',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
