# Generated by Django 4.2.8 on 2024-03-16 07:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningEnglish', '0017_remove_titlegrammar_fk_lesson_remove_word_fk_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
